const i18Obj: Record<string, Record<string, string>> = {
  en: {
    "nav-about": "About",
    "nav-blog": "Blog",
    "nav-catalog": "Catalog",
    "nav-contact": "Contact",
    "nav-cart": "Cart",
    "nav-feedback": "Feedback",
    "nav-gallery": "Gallery",
    "btn-login": "Login",
    "btn-register": "Register",
    "btn-logout": "Logout",
    "btn-admin": "Admin",
    "btn-get-quote": "Get a quote",
    "btn-our-services": "Our services",
    "hero-title": "We provide effective contracting services",
    "hero-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dolor sit varius rhoncus, nullam pulvinar ut sollicitudin dictumst porttitor porttitor quis quisque erat.",
    "hero-explore": "Explore",
    "about-label": "/About Us",
    "about-title": "A team of reliable and experienced contractors",
    "about-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit tristique imperdiet nisi metus, viverra nulla aliquet dui porta porttitor neque lectus diam justo lobortis purus in elit, elementum dignissim nullam vitae pellentesque aliquet aliquam sagittis pulvinar egestas morbi suspendisse eleifend.",
    "about-projects": "Executed Projects",
    "about-experience": "Experience",
    "about-clients": "Satisfied Clients",
    "about-company-btn": "About our company",
    "services-label": "/Our Services",
    "services-title": "A comprehensive set of services",
    "svc-planning-title": "Project Planning",
    "svc-planning-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-management-title": "Project Management",
    "svc-management-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-contracting-title": "General Contracting",
    "svc-contracting-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-interior-title": "Interior Design",
    "svc-interior-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-exterior-title": "Exterior Design",
    "svc-exterior-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-space-title": "Space Planning",
    "svc-space-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-learn-more": "Learn more",
    "parallax-tag": "/Our Promise",
    "parallax-heading": "Built to last, designed to impress",
    "parallax-body": "From the first blueprint to the final finish — we deliver excellence at every stage.",
    "parallax-projects": "Executed Projects",
    "parallax-experience": "Experience",
    "parallax-satisfaction": "Satisfaction",
    "quote-heading": "Ready to pull the trigger? Get a quote today.",
    "quote-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dolor sit varius rhoncus, nullam pulvinar ut sollicitudin dictumst porttitor porttitor quis.",
    "why-label": "/Why Choose Us",
    "why-title-1": "An exceptional quality that can't be beaten",
    "why-desc-1": "Lorem ipsum dolor sit amet, consectetur adipiscing elit tristique rutrum leo quam consectetur urna egestas tincidunt facilisi neque elementum quis lorem posuere dignissim scelerisque aliquam.",
    "why-list-1": "Over 15 years of experience",
    "why-list-2": "200+ successfully executed projects",
    "why-list-3": "Exceptional work quality",
    "why-title-2": "We help you build on your past and prepare for the future",
    "why-desc-2": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dictum nam arcu ac eu orci purus amet eros, id lorem aliquet eget urna at risus sit purus ac magnis blandit eu egestas imperdiet libero.",
    "why-projects": "Successful Projects",
    "why-satisfaction": "Client Satisfaction",
    "projects-label": "/Past Projects",
    "projects-title": "Our project results speak for themselves",
    "project-1-title": "Building construction in Los Angeles, CA",
    "project-1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-1-cat": "Construction",
    "project-2-title": "Kitchen remodeling in Hollywood Hills, CA",
    "project-2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-2-cat": "Remodeling",
    "project-3-title": "Office remodeling in Hollywood Hills, CA",
    "project-3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-3-cat": "Remodeling",
    "testimonials-label": "/Testimonials",
    "testimonials-title": "What our clients say about us and our work",
    "testi-1-quote": "\"A true team of expert contractors\"",
    "testi-1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Convallis senectus non dui vel tortor. Justo lectus integer arcu elit.",
    "testi-1-name": "John Carter",
    "testi-1-location": "Malibu Beach, CA",
    "testi-2-quote": "\"A team that never undelivers\"",
    "testi-2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Convallis senectus non dui vel tortor. Justo lectus integer arcu elit.",
    "testi-2-name": "Lily Woods",
    "testi-2-location": "Hollywood Hills, CA",
    "blog-label": "/Blog",
    "blog-title": "Articles & News",
    "blog-main-title": "12 designers tricks for picking the perfect home color palette",
    "blog-card-1-title": "Paint trends 2022 - the 17 colors you need for the ultimate wonder walls",
    "blog-card-2-title": "Clever DIY home improvements you can do during the pandemic",
    "blog-card-3-title": "15 mind blowing floor designs to make your home look great",
    "findus-label": "/Find Us",
    "findus-title": "Our Locations",
    "findus-office": "Main Office",
    "findus-office-addr": "пр. Независимости, 38<br>Минск, Беларусь",
    "findus-hours": "Working Hours",
    "findus-hours-time": "Mon – Fri: 8:00 – 18:00<br>Sat: 9:00 – 14:00",
    "findus-phone": "Phone",
    "findus-directions": "Get Directions →",
    "footer-desc": "Lorem ipsum dolor sit amet consectetur adipiscing elit.",
    "footer-menu": "Menu",
    "footer-home": "Home",
    "footer-about": "About",
    "footer-blog": "Blog",
    "footer-blog-post": "Blog Post",
    "footer-services": "Services",
    "footer-services-single": "Services Single",
    "footer-shop": "Shop",
    "footer-shop-single": "Shop Single",
    "footer-projects": "Projects",
    "footer-projects-single": "Projects Single",
    "footer-contact": "Contact",
    "footer-utility": "Utility Pages",
    "footer-start": "Start Here",
    "footer-password": "Password Protected",
    "footer-404": "404 Not Found",
    "footer-licenses": "Licenses",
    "footer-styleguide": "Styleguide",
    "footer-changelog": "Changelog",
    "footer-more": "More Webflow Templates",
    "footer-contact-us": "Contact us",
    "footer-call-us": "Call us",
    "footer-email-us": "Email us",
    "catalog-title": "Our Services",
    "catalog-favorites": "Favorites",
    "catalog-cart": "Cart",
    "catalog-home": "← Home",
    "catalog-search-label": "Search",
    "catalog-search-placeholder": "What are you looking for?...",
    "catalog-category-label": "Category",
    "catalog-all-categories": "All categories",
    "catalog-sort-label": "Sort",
    "catalog-sort-default": "Default",
    "catalog-sort-cheap": "Cheapest first",
    "catalog-sort-expensive": "Most expensive",
    "catalog-sort-rating": "Highest rating",
    "catalog-sort-alpha": "A — Z",
    "catalog-price-from": "Price from",
    "catalog-price-to": "Price to",
    "catalog-details": "Details",
    "catalog-add-cart": "Add to cart",
    "catalog-add-fav": "Add to favorites",
    "catalog-loading": "Loading...",
    "catalog-reset": "Reset all",
    "cart-title": "Cart",
    "cart-count": "Items",
    "cart-clear": "Clear cart",
    "cart-empty-title": "Cart is empty",
    "cart-empty-desc": "Add items from the catalog",
    "cart-summary-title": "Total",
    "cart-summary-items": "Items",
    "cart-summary-sum": "Sum",
    "cart-summary-to-pay": "To pay",
    "cart-checkout": "Place order",
    "cart-hint": "By clicking the button, you agree to the terms of service",
    "fav-title": "Favorites",
    "fav-cart": "Cart",
    "fav-catalog": "← Catalog",
    "fav-count": "Loading...",
    "fav-clear": "Clear all",
    "fav-empty-title": "No favorites yet",
    "fav-empty-desc": "Add products to favorites from the catalog",
    "fb-title": "Reviews",
    "fb-home": "← Home",
    "fb-write-title": "Write a review",
    "fb-write-desc": "Leave your feedback about our work",
    "fb-product-label": "Product",
    "fb-product-placeholder": "Select a product...",
    "fb-rating-label": "Rating",
    "fb-message-label": "Message",
    "fb-message-placeholder": "Describe your experience (min 20 characters)",
    "fb-submit": "Submit review",
    "fb-login-hint": "Log in to leave a review",
    "fb-login-btn": "Log in",
    "fb-existing-title": "Reviews",
    "fb-no-reviews": "No reviews yet",
    "gallery-title": "Media Gallery",
    "gallery-home": "← Home",
    "gallery-prev": "← Prev",
    "gallery-random": "⚡ Random",
    "gallery-next": "Next →",
    "gallery-volume": "Volume",
    "gallery-hint": "Space — replay sound · ← → arrows — navigate",
    "login-title": "Sign In",
    "login-subtitle": "Enter your email and password",
    "login-email-label": "Email",
    "login-password-label": "Password",
    "login-password-placeholder": "Enter password",
    "login-submit": "Sign In",
    "login-no-account": "Don't have an account?",
    "login-register": "Sign Up",
    "login-home": "← Home",
    "register-title": "Create Account",
    "register-subtitle": "Fields marked with <span class=\"required-mark\">*</span> are required",
    "register-personal": "Personal Information",
    "register-firstname": "First Name",
    "register-lastname": "Last Name",
    "register-middlename": "Middle Name",
    "register-middlename-opt": "(optional)",
    "register-account": "Account",
    "register-nickname": "Nickname",
    "register-generate": "Generate",
    "register-avail-attempts": "Attempts available: 5",
    "register-phone-hint": "Belarusian numbers only: operators 25, 29, 33, 44",
    "register-birthdate": "Date of Birth",
    "register-age-hint": "Must be at least 16 years old",
    "register-security": "Security",
    "register-password-hint": "8–20 characters: uppercase, lowercase, digit, special char",
    "register-confirm-pwd": "Confirm Password",
    "register-confirm-pwd-hint": "Paste from clipboard is disabled",
    "register-agreement": "I accept",
    "register-terms": "terms of use",
    "register-and": "and",
    "register-privacy": "privacy policy",
    "register-submit": "Sign Up",
    "admin-title": "Admin Panel",
    "admin-catalog": "Catalog",
    "admin-home": "← Home",
    "admin-products": "Products",
    "admin-new-product": "+ New product",
    "admin-reviews": "Reviews",
    "admin-filter-product": "By product",
    "admin-filter-user": "By user",
    "admin-modal-title-new": "New product",
    "admin-modal-title-edit": "Edit product",
    "admin-field-title": "Title",
    "admin-field-desc": "Description",
    "admin-field-category": "Category",
    "admin-field-price": "Price ($)",
    "admin-field-rating": "Rating (1–5)",
    "admin-field-image": "Image URL",
    "admin-submit-create": "Create",
    "admin-submit-update": "Update",
    "admin-delete-title": "Delete product?",
    "admin-delete-desc": "This action is irreversible. The product will be permanently deleted.",
    "admin-delete-cancel": "Cancel",
    "admin-delete-confirm": "Delete",
    "admin-select-placeholder": "— select —",
    "admin-select-category": "— select category —",
    "admin-or": "or",
    "profile-title": "Personal Data",
    "profile-firstname": "First Name",
    "profile-lastname": "Last Name",
    "profile-middlename": "Middle Name",
    "profile-nickname": "Nickname",
    "profile-email": "Email",
    "profile-phone": "Phone",
    "profile-birthdate": "Date of Birth",
    "profile-save": "Save",
    "profile-close": "Close",
    "profile-reset": "Reset Settings",
  },
  ru: {
    "nav-about": "О нас",
    "nav-blog": "Блог",
    "nav-catalog": "Каталог",
    "nav-contact": "Контакты",
    "nav-cart": "Корзина",
    "nav-feedback": "Отзывы",
    "nav-gallery": "Галерея",
    "btn-login": "Войти",
    "btn-register": "Регистрация",
    "btn-logout": "Выйти",
    "btn-admin": "Админ",
    "btn-get-quote": "Получить расчёт",
    "btn-our-services": "Наши услуги",
    "hero-title": "Мы предоставляем эффективные услуги подряда",
    "hero-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dolor sit varius rhoncus, nullam pulvinar ut sollicitudin dictumst porttitor porttitor quis quisque erat.",
    "hero-explore": "Подробнее",
    "about-label": "/О нас",
    "about-title": "Команда надёжных и опытных подрядчиков",
    "about-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit tristique imperdiet nisi metus, viverra nulla aliquet dui porta porttitor neque lectus diam justo lobortis purus in elit, elementum dignissim nullam vitae pellentesque aliquet aliquam sagittis pulvinar egestas morbi suspendisse eleifend.",
    "about-projects": "Выполненных проектов",
    "about-experience": "Опыт",
    "about-clients": "Довольных клиентов",
    "about-company-btn": "О нашей компании",
    "services-label": "/Наши услуги",
    "services-title": "Полный набор услуг",
    "svc-planning-title": "Планирование проектов",
    "svc-planning-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-management-title": "Управление проектами",
    "svc-management-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-contracting-title": "Генеральный подряд",
    "svc-contracting-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-interior-title": "Дизайн интерьера",
    "svc-interior-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-exterior-title": "Дизайн экстерьера",
    "svc-exterior-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-space-title": "Планировка пространства",
    "svc-space-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit quis eget morbi fermentum sagittis, et mi lacus ornare tincidunt id.",
    "svc-learn-more": "Подробнее",
    "parallax-tag": "/Наше обещание",
    "parallax-heading": "Создано для долговечности, впечатляет дизайном",
    "parallax-body": "От первого чертежа до финальной отделки — мы обеспечиваем excellence на каждом этапе.",
    "parallax-projects": "Выполненных проектов",
    "parallax-experience": "Опыт",
    "parallax-satisfaction": "Удовлетворённость",
    "quote-heading": "Готовы начать? Получите расчёт сегодня.",
    "quote-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dolor sit varius rhoncus, nullam pulvinar ut sollicitudin dictumst porttitor porttitor quis.",
    "why-label": "/Почему мы",
    "why-title-1": "Исключительное качество, которое невозможно превзойти",
    "why-desc-1": "Lorem ipsum dolor sit amet, consectetur adipiscing elit tristique rutrum leo quam consectetur urna egestas tincidunt facilisi neque elementum quis lorem posuere dignissim scelerisque aliquam.",
    "why-list-1": "Более 15 лет опыта",
    "why-list-2": "200+ успешно выполненных проектов",
    "why-list-3": "Исключительное качество работы",
    "why-title-2": "Мы помогаем вам опираться на прошлое и готовиться к будущему",
    "why-desc-2": "Lorem ipsum dolor sit amet, consectetur adipiscing elit dictum nam arcu ac eu orci purus amet eros, id lorem aliquet eget urna at risus sit purus ac magnis blandit eu egestas imperdiet libero.",
    "why-projects": "Успешных проектов",
    "why-satisfaction": "Удовлетворённость клиентов",
    "projects-label": "/Прошлые проекты",
    "projects-title": "Результаты наших проектов говорят сами за себя",
    "project-1-title": "Строительство здания в Лос-Анджелесе, Калифорния",
    "project-1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-1-cat": "Строительство",
    "project-2-title": "Ремонт кухни в Голливуд Хиллз, Калифорния",
    "project-2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-2-cat": "Ремонт",
    "project-3-title": "Ремонт офиса в Голливуд Хиллз, Калифорния",
    "project-3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit lectus aenean sit elementum pellentesque ultrices sem.",
    "project-3-cat": "Ремонт",
    "testimonials-label": "/Отзывы",
    "testimonials-title": "Что говорят наши клиенты о нас и нашей работе",
    "testi-1-quote": "\"Настоящая команда экспертных подрядчиков\"",
    "testi-1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Convallis senectus non dui vel tortor. Justo lectus integer arcu elit.",
    "testi-1-name": "Джон Картер",
    "testi-1-location": "Малибу Бич, Калифорния",
    "testi-2-quote": "\"Команда, которая никогда не подводит\"",
    "testi-2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Convallis senectus non dui vel tortor. Justo lectus integer arcu elit.",
    "testi-2-name": "Лили Вудс",
    "testi-2-location": "Голливуд Хиллз, Калифорния",
    "blog-label": "/Блог",
    "blog-title": "Статьи и новости",
    "blog-main-title": "12 приёмов дизайнеров для выбора идеальной палитры цветов для дома",
    "blog-card-1-title": "Тренды красок 2022 — 17 цветов для идеальных стен",
    "blog-card-2-title": "Умные DIY-улучшения дома, которые можно сделать во время пандемии",
    "blog-card-3-title": "15 потрясающих дизайнов пола, которые сделают ваш дом великолепным",
    "findus-label": "/Найти нас",
    "findus-title": "Наши адреса",
    "findus-office": "Главный офис",
    "findus-office-addr": "пр. Независимости, 38<br>Минск, Беларусь",
    "findus-hours": "Часы работы",
    "findus-hours-time": "Пн – Пт: 8:00 – 18:00<br>Сб: 9:00 – 14:00",
    "findus-phone": "Телефон",
    "findus-directions": "Маршрут →",
    "footer-desc": "Lorem ipsum dolor sit amet consectetur adipiscing elit.",
    "footer-menu": "Меню",
    "footer-home": "Главная",
    "footer-about": "О нас",
    "footer-blog": "Блог",
    "footer-blog-post": "Запись блога",
    "footer-services": "Услуги",
    "footer-services-single": "Услуга",
    "footer-shop": "Магазин",
    "footer-shop-single": "Товар магазина",
    "footer-projects": "Проекты",
    "footer-projects-single": "Проект",
    "footer-contact": "Контакты",
    "footer-utility": "Полезные страницы",
    "footer-start": "Начать здесь",
    "footer-password": "Защищено паролем",
    "footer-404": "404 Не найдено",
    "footer-licenses": "Лицензии",
    "footer-styleguide": "Гайд по стилю",
    "footer-changelog": "История изменений",
    "footer-more": "Больше шаблонов Webflow",
    "footer-contact-us": "Свяжитесь с нами",
    "footer-call-us": "Позвонить",
    "footer-email-us": "Написать",
    "catalog-title": "Наши услуги",
    "catalog-favorites": "Избранное",
    "catalog-cart": "Корзина",
    "catalog-home": "← На главную",
    "catalog-search-label": "Поиск",
    "catalog-search-placeholder": "Что вы ищете?...",
    "catalog-category-label": "Категория",
    "catalog-all-categories": "Все категории",
    "catalog-sort-label": "Сортировка",
    "catalog-sort-default": "По умолчанию",
    "catalog-sort-cheap": "Сначала дешёвые",
    "catalog-sort-expensive": "Сначала дорогие",
    "catalog-sort-rating": "Высокий рейтинг",
    "catalog-sort-alpha": "А — Я",
    "catalog-price-from": "Цена от",
    "catalog-price-to": "Цена до",
    "catalog-details": "Детали",
    "catalog-add-cart": "В корзину",
    "catalog-add-fav": "В избранное",
    "catalog-loading": "Загрузка...",
    "catalog-reset": "Сбросить всё",
    "cart-title": "Корзина",
    "cart-count": "Позиций",
    "cart-clear": "Очистить корзину",
    "cart-empty-title": "Корзина пуста",
    "cart-empty-desc": "Добавьте товары из каталога",
    "cart-summary-title": "Итого",
    "cart-summary-items": "Позиций",
    "cart-summary-sum": "Сумма",
    "cart-summary-to-pay": "К оплате",
    "cart-checkout": "Оформить заказ",
    "cart-hint": "Нажимая кнопку, вы соглашаетесь с условиями сервиса",
    "fav-title": "Избранное",
    "fav-cart": "Корзина",
    "fav-catalog": "← Каталог",
    "fav-count": "Загрузка...",
    "fav-clear": "Очистить всё",
    "fav-empty-title": "Нет избранных",
    "fav-empty-desc": "Добавьте товары в избранное из каталога",
    "fb-title": "Отзывы",
    "fb-home": "← На главную",
    "fb-write-title": "Написать отзыв",
    "fb-write-desc": "Оставьте свой отзыв о нашей работе",
    "fb-product-label": "Товар",
    "fb-product-placeholder": "Выберите товар...",
    "fb-rating-label": "Рейтинг",
    "fb-message-label": "Сообщение",
    "fb-message-placeholder": "Опишите ваш опыт (минимум 20 символов)",
    "fb-submit": "Отправить отзыв",
    "fb-login-hint": "Войдите, чтобы оставить отзыв",
    "fb-login-btn": "Войти",
    "fb-existing-title": "Отзывы",
    "fb-no-reviews": "Пока нет отзывов",
    "gallery-title": "Медиа Галерея",
    "gallery-home": "← На главную",
    "gallery-prev": "← Назад",
    "gallery-random": "⚡ Случайно",
    "gallery-next": "Далее →",
    "gallery-volume": "Громкость",
    "gallery-hint": "Пробел — повтор звука · ← → стрелки — навигация",
    "login-title": "Вход в аккаунт",
    "login-subtitle": "Введите email и пароль от вашего аккаунта",
    "login-email-label": "Email",
    "login-password-label": "Пароль",
    "login-password-placeholder": "Введите пароль",
    "login-submit": "Войти",
    "login-no-account": "Нет аккаунта?",
    "login-register": "Зарегистрироваться",
    "login-home": "← На главную",
    "register-title": "Создать аккаунт",
    "register-subtitle": "Поля, отмеченные <span class=\"required-mark\">*</span>, обязательны",
    "register-personal": "Личные данные",
    "register-firstname": "Имя",
    "register-lastname": "Фамилия",
    "register-middlename": "Отчество",
    "register-middlename-opt": "(необязательно)",
    "register-account": "Аккаунт",
    "register-nickname": "Никнейм",
    "register-generate": "Сгенерировать",
    "register-avail-attempts": "Доступно попыток: 5",
    "register-phone-hint": "Только белорусские номера: операторы 25, 29, 33, 44",
    "register-birthdate": "Дата рождения",
    "register-age-hint": "Возраст должен быть не менее 16 лет",
    "register-security": "Безопасность",
    "register-password-hint": "8–20 символов: заглавная буква, строчная, цифра, спецсимвол",
    "register-confirm-pwd": "Повторите пароль",
    "register-confirm-pwd-hint": "Вставка из буфера обмена отключена",
    "register-agreement": "Я принимаю",
    "register-terms": "условия использования",
    "register-and": "и",
    "register-privacy": "политику конфиденциальности",
    "register-submit": "Зарегистрироваться",
    "admin-title": "Панель администратора",
    "admin-catalog": "Каталог",
    "admin-home": "← На главную",
    "admin-products": "Товары",
    "admin-new-product": "+ Новый товар",
    "admin-reviews": "Отзывы",
    "admin-filter-product": "По товару",
    "admin-filter-user": "По пользователю",
    "admin-modal-title-new": "Новый товар",
    "admin-modal-title-edit": "Редактировать товар",
    "admin-field-title": "Название",
    "admin-field-desc": "Описание",
    "admin-field-category": "Категория",
    "admin-field-price": "Цена ($)",
    "admin-field-rating": "Рейтинг (1–5)",
    "admin-field-image": "URL изображения",
    "admin-submit-create": "Создать",
    "admin-submit-update": "Обновить",
    "admin-delete-title": "Удалить товар?",
    "admin-delete-desc": "Это действие необратимо. Товар будет удалён навсегда.",
    "admin-delete-cancel": "Отмена",
    "admin-delete-confirm": "Удалить",
    "admin-select-placeholder": "— выберите —",
    "admin-select-category": "— выберите —",
    "admin-or": "или",
    "profile-title": "Личные данные",
    "profile-firstname": "Имя",
    "profile-lastname": "Фамилия",
    "profile-middlename": "Отчество",
    "profile-nickname": "Никнейм",
    "profile-email": "Email",
    "profile-phone": "Телефон",
    "profile-birthdate": "Дата рождения",
    "profile-save": "Сохранить",
    "profile-close": "Закрыть",
    "profile-reset": "Сбросить настройки",
  },
};

export let currentLang = "en";

export function setCurrentLang(lang: string): void {
  currentLang = lang;
}

export function getTranslate(lang: string): void {
  currentLang = lang;
  const elements = document.querySelectorAll<HTMLElement>("[data-i18n]");
  elements.forEach((el) => {
    const key = el.dataset.i18n;
    if (key && i18Obj[lang]?.[key]) {
      el.textContent = i18Obj[lang][key];
    }
  });
}
